using Ambev.DeveloperEvaluation.Domain.Common;
using Ambev.DeveloperEvaluation.Domain.Enums;
using Ambev.DeveloperEvaluation.Domain.Events;
using Ambev.DeveloperEvaluation.Domain.Exceptions;
using Ambev.DeveloperEvaluation.Domain.ValueObjects;

namespace Ambev.DeveloperEvaluation.Domain.Entities;

/// <summary>
/// Input for one line of a sale.
/// </summary>
public record SaleItemInput(ProductRef Product, int Quantity);

/// <summary>
/// Aggregate root for a sale. Customer, branch and products are referenced through
/// external identities with denormalized descriptions.
/// All state changes go through methods so that invariants hold and domain events are raised.
/// </summary>
public class Sale : BaseEntity
{
    private readonly List<SaleItem> _items = new();

    /// <summary>Sequential, human-readable sale number generated by the database.</summary>
    public long SaleNumber { get; private set; }

    /// <summary>Date and time (UTC) when the sale was made.</summary>
    public DateTime SaleDate { get; private set; }

    /// <summary>External identity of the customer.</summary>
    public CustomerRef Customer { get; private set; } = default!;

    /// <summary>External identity of the branch where the sale was made.</summary>
    public BranchRef Branch { get; private set; } = default!;

    /// <summary>Whether the sale is active or cancelled.</summary>
    public SaleStatus Status { get; private set; }

    /// <summary>Sum of the totals of all non-cancelled items.</summary>
    public decimal TotalAmount { get; private set; }

    public DateTime CreatedAt { get; private set; }

    public DateTime? UpdatedAt { get; private set; }

    /// <summary>Items of the sale. Mutated only through <see cref="Update"/> and <see cref="CancelItem"/>.</summary>
    public IReadOnlyCollection<SaleItem> Items => _items.AsReadOnly();

    // Required by EF Core
    private Sale()
    {
    }

    /// <summary>
    /// Creates an active sale and raises <see cref="SaleCreatedEvent"/>.
    /// </summary>
    public static Sale Create(DateTime saleDate, CustomerRef customer, BranchRef branch, IEnumerable<SaleItemInput> items)
    {
        var sale = new Sale
        {
            Id = Guid.NewGuid(),
            SaleDate = saleDate,
            Customer = customer,
            Branch = branch,
            Status = SaleStatus.Active,
            CreatedAt = DateTime.UtcNow
        };

        sale.ReplaceItems(items);
        sale.AddDomainEvent(new SaleCreatedEvent(sale));
        return sale;
    }

    /// <summary>
    /// Replaces header and items (PUT semantics) and raises <see cref="SaleModifiedEvent"/>.
    /// </summary>
    public void Update(DateTime saleDate, CustomerRef customer, BranchRef branch, IEnumerable<SaleItemInput> items)
    {
        EnsureActive();

        SaleDate = saleDate;
        Customer = customer;
        Branch = branch;
        ReplaceItems(items);
        UpdatedAt = DateTime.UtcNow;

        AddDomainEvent(new SaleModifiedEvent(this));
    }

    /// <summary>
    /// Cancels one item, recalculates the total and raises <see cref="ItemCancelledEvent"/>.
    /// </summary>
    /// <exception cref="KeyNotFoundException">The item does not belong to this sale.</exception>
    public void CancelItem(Guid itemId)
    {
        EnsureActive();

        var item = _items.FirstOrDefault(i => i.Id == itemId)
            ?? throw new KeyNotFoundException($"Item {itemId} not found in sale {Id}");

        item.Cancel();
        Recalculate();
        UpdatedAt = DateTime.UtcNow;

        AddDomainEvent(new ItemCancelledEvent(this, item));
    }

    /// <summary>
    /// Cancels the whole sale and raises <see cref="SaleCancelledEvent"/>.
    /// </summary>
    public void Cancel()
    {
        EnsureActive();

        Status = SaleStatus.Cancelled;
        UpdatedAt = DateTime.UtcNow;

        AddDomainEvent(new SaleCancelledEvent(this));
    }

    private void ReplaceItems(IEnumerable<SaleItemInput> items)
    {
        var inputs = items.ToList();

        if (inputs.Count == 0)
            throw new DomainException("A sale must have at least one item");

        var duplicate = inputs.GroupBy(i => i.Product.Id).FirstOrDefault(g => g.Count() > 1);
        if (duplicate != null)
            throw new DomainException($"Product {duplicate.Key} appears more than once (duplicate lines would bypass the 20-item limit)");

        _items.Clear();
        _items.AddRange(inputs.Select(i => new SaleItem(Id, i.Product, i.Quantity)));
        Recalculate();
    }

    private void Recalculate()
    {
        TotalAmount = _items.Where(i => !i.IsCancelled).Sum(i => i.TotalAmount);
    }

    private void EnsureActive()
    {
        if (Status == SaleStatus.Cancelled)
            throw new DomainException($"Sale {SaleNumber} is cancelled and cannot be modified");
    }
}
